spring:
  profiles:
    active: db
  messages:
    encoding: UTF-8

logging:
  level:
    root:  ERROR
    org.springframework:  ERROR
    org.mybatis:  DEBUG
    com.example.learn:  INFO
  file: logfile.log
#  path: app/logs
  pattern:
    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'




